import {prisma} from "../src/services/config/prisma";

async function main() {
  await prisma.countryCode.createMany({
    data: [
      { countryName: "India", countryCode: "+91" },
      { countryName: "Afghanistan", countryCode: "+93" },
      { countryName: "Albania", countryCode: "+355" },
      { countryName: "Algeria", countryCode: "+213" },
      { countryName: "Andorra", countryCode: "+376" },
      { countryName: "Angola", countryCode: "+244" },
      { countryName: "Argentina", countryCode: "+54" },
      { countryName: "Armenia", countryCode: "+374" },
      { countryName: "Australia", countryCode: "+61" },
      { countryName: "Austria", countryCode: "+43" },
      { countryName: "Azerbaijan", countryCode: "+994" },
      { countryName: "Bahrain", countryCode: "+973" },
      { countryName: "Bangladesh", countryCode: "+880" },
      { countryName: "Belarus", countryCode: "+375" },
      { countryName: "Belgium", countryCode: "+32" },
      { countryName: "Belize", countryCode: "+501" },
      { countryName: "Benin", countryCode: "+229" },
      { countryName: "Bhutan", countryCode: "+975" },
      { countryName: "Bolivia", countryCode: "+591" },
      { countryName: "Bosnia and Herzegovina", countryCode: "+387" },
      { countryName: "Botswana", countryCode: "+267" },
      { countryName: "Brazil", countryCode: "+55" },
      { countryName: "Brunei", countryCode: "+673" },
      { countryName: "Bulgaria", countryCode: "+359" },
      { countryName: "Burkina Faso", countryCode: "+226" },
      { countryName: "Burundi", countryCode: "+257" },
      { countryName: "Cambodia", countryCode: "+855" },
      { countryName: "Cameroon", countryCode: "+237" },
      { countryName: "Canada", countryCode: "+1" },
      { countryName: "Cape Verde", countryCode: "+238" },
      { countryName: "Chad", countryCode: "+235" },
      { countryName: "Chile", countryCode: "+56" },
      { countryName: "China", countryCode: "+86" },
      { countryName: "Colombia", countryCode: "+57" },
      { countryName: "Comoros", countryCode: "+269" },
      { countryName: "Congo", countryCode: "+242" },
      { countryName: "Costa Rica", countryCode: "+506" },
      { countryName: "Croatia", countryCode: "+385" },
      { countryName: "Cuba", countryCode: "+53" },
      { countryName: "Cyprus", countryCode: "+357" },
      { countryName: "Czech Republic", countryCode: "+420" },
      { countryName: "Denmark", countryCode: "+45" },
      { countryName: "Djibouti", countryCode: "+253" },
      { countryName: "Dominican Republic", countryCode: "+1-809" },
      { countryName: "Ecuador", countryCode: "+593" },
      { countryName: "Egypt", countryCode: "+20" },
      { countryName: "El Salvador", countryCode: "+503" },
      { countryName: "Estonia", countryCode: "+372" },
      { countryName: "Ethiopia", countryCode: "+251" },
      { countryName: "Fiji", countryCode: "+679" },
      { countryName: "Finland", countryCode: "+358" },
      { countryName: "France", countryCode: "+33" },
      { countryName: "Gabon", countryCode: "+241" },
      { countryName: "Gambia", countryCode: "+220" },
      { countryName: "Georgia", countryCode: "+995" },
      { countryName: "Germany", countryCode: "+49" },
      { countryName: "Ghana", countryCode: "+233" },
      { countryName: "Greece", countryCode: "+30" },
      { countryName: "Greenland", countryCode: "+299" },
      { countryName: "Guatemala", countryCode: "+502" },
      { countryName: "Haiti", countryCode: "+509" },
      { countryName: "Honduras", countryCode: "+504" },
      { countryName: "Hong Kong", countryCode: "+852" },
      { countryName: "Hungary", countryCode: "+36" },
      { countryName: "Iceland", countryCode: "+354" },
      { countryName: "Indonesia", countryCode: "+62" },
      { countryName: "Iran", countryCode: "+98" },
      { countryName: "Iraq", countryCode: "+964" },
      { countryName: "Ireland", countryCode: "+353" },
      { countryName: "Israel", countryCode: "+972" },
      { countryName: "Italy", countryCode: "+39" },
      { countryName: "Jamaica", countryCode: "+1-876" },
      { countryName: "Japan", countryCode: "+81" },
      { countryName: "Jordan", countryCode: "+962" },
      { countryName: "Kazakhstan", countryCode: "+7" },
      { countryName: "Kenya", countryCode: "+254" },
      { countryName: "Kuwait", countryCode: "+965" },
      { countryName: "Kyrgyzstan", countryCode: "+996" },
      { countryName: "Laos", countryCode: "+856" },
      { countryName: "Latvia", countryCode: "+371" },
      { countryName: "Lebanon", countryCode: "+961" },
      { countryName: "Libya", countryCode: "+218" },
      { countryName: "Liechtenstein", countryCode: "+423" },
      { countryName: "Lithuania", countryCode: "+370" },
      { countryName: "Luxembourg", countryCode: "+352" },
      { countryName: "Macao", countryCode: "+853" },
      { countryName: "Madagascar", countryCode: "+261" },
      { countryName: "Malawi", countryCode: "+265" },
      { countryName: "Malaysia", countryCode: "+60" },
      { countryName: "Maldives", countryCode: "+960" },
      { countryName: "Mali", countryCode: "+223" },
      { countryName: "Malta", countryCode: "+356" },
      { countryName: "Mexico", countryCode: "+52" },
      { countryName: "Moldova", countryCode: "+373" },
      { countryName: "Monaco", countryCode: "+377" },
      { countryName: "Mongolia", countryCode: "+976" },
      { countryName: "Montenegro", countryCode: "+382" },
      { countryName: "Morocco", countryCode: "+212" },
      { countryName: "Mozambique", countryCode: "+258" },
      { countryName: "Myanmar (Burma)", countryCode: "+95" },
      { countryName: "Namibia", countryCode: "+264" },
      { countryName: "Nepal", countryCode: "+977" },
      { countryName: "Netherlands", countryCode: "+31" },
      { countryName: "New Zealand", countryCode: "+64" },
      { countryName: "Nigeria", countryCode: "+234" },
      { countryName: "North Korea", countryCode: "+850" },
      { countryName: "Norway", countryCode: "+47" },
      { countryName: "Oman", countryCode: "+968" },
      { countryName: "Pakistan", countryCode: "+92" },
      { countryName: "Palestine", countryCode: "+970" },
      { countryName: "Panama", countryCode: "+507" },
      { countryName: "Papua New Guinea", countryCode: "+675" },
      { countryName: "Paraguay", countryCode: "+595" },
      { countryName: "Peru", countryCode: "+51" },
      { countryName: "Philippines", countryCode: "+63" },
      { countryName: "Poland", countryCode: "+48" },
      { countryName: "Portugal", countryCode: "+351" },
      { countryName: "Qatar", countryCode: "+974" },
      { countryName: "Romania", countryCode: "+40" },
      { countryName: "Russia", countryCode: "+7" },
      { countryName: "Rwanda", countryCode: "+250" },
      { countryName: "Saudi Arabia", countryCode: "+966" },
      { countryName: "Senegal", countryCode: "+221" },
      { countryName: "Serbia", countryCode: "+381" },
      { countryName: "Singapore", countryCode: "+65" },
      { countryName: "Slovakia", countryCode: "+421" },
      { countryName: "Slovenia", countryCode: "+386" },
      { countryName: "Somalia", countryCode: "+252" },
      { countryName: "South Africa", countryCode: "+27" },
      { countryName: "South Korea", countryCode: "+82" },
      { countryName: "Spain", countryCode: "+34" },
      { countryName: "Sri Lanka", countryCode: "+94" },
      { countryName: "Sudan", countryCode: "+249" },
      { countryName: "Sweden", countryCode: "+46" },
      { countryName: "Switzerland", countryCode: "+41" },
      { countryName: "Syria", countryCode: "+963" },
      { countryName: "Taiwan", countryCode: "+886" },
      { countryName: "Tanzania", countryCode: "+255" },
      { countryName: "Thailand", countryCode: "+66" },
      { countryName: "Tunisia", countryCode: "+216" },
      { countryName: "Turkey", countryCode: "+90" },
      { countryName: "Uganda", countryCode: "+256" },
      { countryName: "Ukraine", countryCode: "+380" },
      { countryName: "United Arab Emirates", countryCode: "+971" },
      { countryName: "United Kingdom", countryCode: "+44" },
      { countryName: "United States", countryCode: "+1" },
      { countryName: "Uruguay", countryCode: "+598" },
      { countryName: "Uzbekistan", countryCode: "+998" },
      { countryName: "Venezuela", countryCode: "+58" },
      { countryName: "Vietnam", countryCode: "+84" },
      { countryName: "Yemen", countryCode: "+967" },
      { countryName: "Zambia", countryCode: "+260" },
      { countryName: "Zimbabwe", countryCode: "+263" },
    ],
    skipDuplicates: true, // avoids inserting duplicates if rerun
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
